apiVersion: v1
name: Casa Padel Sfax
description: A web application for a padel club with features of tournaments, reservations and sponsors
version: 0.1.0

dependencies: 
  - name: redis
    repository: https://charts.bitnami.com/bitnami  
    version: 17.x.x  