deployment:
    replica: 2
    # imageName: mahdihamdi99/casapadelsfax
    imageName: ramezbenaribia/casapadelsfax
    imageTag: latest
    httpPort: 3000

mongodb:
    DATABASE_USER: YWRtaW4=
    DATABASE_PASSWORD: YWRtaW4=        

    