apiVersion: v1
kind: Service
metadata:
  name: backend-microservice-reservation-svc
  namespace: staging
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port : "3000"
spec:
  selector:
    app: backend-microservice-reservation
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.deployment.httpPort }}
      targetPort: 3000