version: "3.3"
services:
  casapadel_sfax:
    container_name: casapadel_sfax
    build:
      context: ./
    command: "npm run start:dev"
    ports:
      - 80:3000
    networks:
      - casapadel
    environment:
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_LINK=casapadel_sfax_mongodb:27017
  mongo:
    container_name: casapadel_sfax_mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbData:/data/db
    networks:
      - casapadel
    environment:
    - MONGO_INITDB_DATABASE=casapadel_sfax
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=admin
volumes:
  mongodbData: {}
networks:
  casapadel: {}
