

version: "3"

networks:
  loki:

services:
  # Observability services


  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - ./data/loki/data:/data/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki


 
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

  prometheus:
    image: prom/prometheus:latest
    user: root
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - /var/log:/var/log
      - ./config/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - ./data/api/:/usr/api/data/
    # command: -config.file=/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - loki


  grafana:
    image: grafana/grafana:latest
    environment: 
      # Disable authentication
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./config/provisioning/:/etc/grafana/provisioning
    ports:
      - 3000:3000
    networks:
      - loki
