apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: staging
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.deployment.httpPort }}
      targetPort: 3000