apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: staging
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port : "3000"
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: {{ .Values.deployment.httpPort }}