apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: staging
type: Opaque
data:
    DATABASE_USER: {{ .Values.mongodb.DATABASE_USER }}
    DATABASE_PASSWORD: {{ .Values.mongodb.DATABASE_PASSWORD }}