apiVersion: v1
kind: Service
metadata:
  name: backend-mongodb-svc
  namespace: staging
spec:
  type: ClusterIP
  selector:
    app: backend-mongodb
  ports:
    - name: backend-mongodb
      protocol: TCP
      port: 27017 #service port
      targetPort: 27017 #pod port