apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: casapadel-backend-azure-managed-disk
  namespace: staging
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi